# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.

# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: digit360_proto_v1.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

import betterproto


class LightingChannel(betterproto.Enum):
    CHANNEL_NONE = 0
    CHANNEL_1 = 1
    CHANNEL_2 = 2
    CHANNEL_3 = 3
    CHANNEL_4 = 4
    CHANNEL_5 = 5
    CHANNEL_6 = 6
    CHANNEL_7 = 7
    CHANNEL_8 = 8
    CHANNEL_ALL = 9
    CHANNEL_1ST_HALF = 10
    CHANNEL_2ND_HALF = 11
    CHANNEL_ALL_RESET = 12


class ImuDataType(betterproto.Enum):
    NONE_IMU = 0
    ACC = 1
    GYRO = 2
    MAG = 3
    QUAT = 4
    EULER = 5
    AUX_IMU = 6


class ResetType(betterproto.Enum):
    NONE_RESET = 0
    ICS_BOOTLOADER = 1
    MCU_RESET = 2
    NCU_RESET = 3
    MCU_BOOTLOADER = 4


class PressureConfigTypes(betterproto.Enum):
    NONE_PRESSURE_CONFIG = 0
    OVERSAMPLING_1X = 1
    OVERSAMPLING_2X = 2
    OVERSAMPLING_4X = 3
    OVERSAMPLING_8X = 4
    OVERSAMPLING_16X = 5
    OVERSAMPLING_32X = 6
    OVERSAMPLING_64X = 7
    OVERSAMPLING_128X = 8
    IIR_FILTER_BYPASS = 9
    IIR_FILTER_COEFF_1 = 10
    IIR_FILTER_COEFF_3 = 11
    IIR_FILTER_COEFF_7 = 12
    IIR_FILTER_COEFF_15 = 13
    IIR_FILTER_COEFF_31 = 14
    IIR_FILTER_COEFF_63 = 15
    IIR_FILTER_COEFF_127 = 16


@dataclass(eq=False, repr=False)
class LightingControl(betterproto.Message):
    alpha: float = betterproto.float_field(1)
    channel: "LightingChannel" = betterproto.enum_field(2)
    r: int = betterproto.int32_field(3)
    g: int = betterproto.int32_field(4)
    b: int = betterproto.int32_field(5)


@dataclass(eq=False, repr=False)
class PressureControl(betterproto.Message):
    osr_t: "PressureConfigTypes" = betterproto.enum_field(2)
    osr_p: "PressureConfigTypes" = betterproto.enum_field(3)
    iir_t: "PressureConfigTypes" = betterproto.enum_field(4)
    iir_p: "PressureConfigTypes" = betterproto.enum_field(5)
    shadow_iir_t_enable: bool = betterproto.bool_field(6)
    shadow_iir_p_enable: bool = betterproto.bool_field(7)


@dataclass(eq=False, repr=False)
class RawImuData(betterproto.Message):
    sensor: "ImuDataType" = betterproto.enum_field(1)
    ts_ght: int = betterproto.uint64_field(2)
    x: float = betterproto.float_field(3)
    y: float = betterproto.float_field(4)
    z: float = betterproto.float_field(5)


@dataclass(eq=False, repr=False)
class EulerData(betterproto.Message):
    ts_ght: int = betterproto.uint64_field(1)
    heading: float = betterproto.float_field(2)
    pitch: float = betterproto.float_field(3)
    roll: float = betterproto.float_field(4)


@dataclass(eq=False, repr=False)
class QuatData(betterproto.Message):
    ts_ght: int = betterproto.uint64_field(1)
    x: float = betterproto.float_field(2)
    y: float = betterproto.float_field(3)
    z: float = betterproto.float_field(4)
    w: float = betterproto.float_field(5)
    accuracy: float = betterproto.float_field(6)


@dataclass(eq=False, repr=False)
class ImuData(betterproto.Message):
    ts: int = betterproto.uint32_field(1)
    raw: "RawImuData" = betterproto.message_field(2, group="imu_type")
    euler: "EulerData" = betterproto.message_field(3, group="imu_type")
    quat: "QuatData" = betterproto.message_field(4, group="imu_type")


@dataclass(eq=False, repr=False)
class GasHtData(betterproto.Message):
    ts: int = betterproto.uint32_field(2)
    ts_ght: int = betterproto.uint64_field(3)
    temperature: float = betterproto.float_field(4)
    pressure: float = betterproto.float_field(5)
    humidity: float = betterproto.float_field(6)
    gas: float = betterproto.float_field(7)
    gas_index: float = betterproto.float_field(8)


@dataclass(eq=False, repr=False)
class PressureApData(betterproto.Message):
    ts: int = betterproto.uint32_field(1)
    channel_a: bytes = betterproto.bytes_field(2)
    channel_b: bytes = betterproto.bytes_field(3)


@dataclass(eq=False, repr=False)
class PressureData(betterproto.Message):
    ts: int = betterproto.uint32_field(1)
    pressure: float = betterproto.float_field(2)
    temperature: float = betterproto.float_field(3)


@dataclass(eq=False, repr=False)
class SystemData(betterproto.Message):
    version_minor: int = betterproto.int32_field(1)
    version_major: int = betterproto.int32_field(2)
    status: int = betterproto.int32_field(3)
    reset: "ResetType" = betterproto.enum_field(4)


@dataclass(eq=False, repr=False)
class Digit360Message(betterproto.Message):
    system_data: "SystemData" = betterproto.message_field(1, group="type")
    pressure_data: "PressureData" = betterproto.message_field(2, group="type")
    pressure_ap_data: "PressureApData" = betterproto.message_field(3, group="type")
    gasht_data: "GasHtData" = betterproto.message_field(4, group="type")
    imu_data: "ImuData" = betterproto.message_field(5, group="type")
    pressure_control: "PressureControl" = betterproto.message_field(6, group="type")
    lighting_control: "LightingControl" = betterproto.message_field(7, group="type")
